# Generated by Django 4.1.2 on 2022-11-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_personalinfo_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='email',
            new_name='user_name',
        ),
    ]
