# Generated by Django 4.1.2 on 2022-11-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_email_personalinfo_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='user_name',
            new_name='email',
        ),
    ]
