# Generated by Django 4.1.2 on 2022-11-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_user_name_personalinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='carrepair',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='phonenumber',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='tailor',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='transport',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='tutor',
            field=models.BooleanField(null=True),
        ),
    ]
