# Generated by Django 4.1.2 on 2022-11-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_personalinfo_carrepair_personalinfo_phonenumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='phonenumber',
            new_name='phoneNumber',
        ),
    ]
