# Generated by Django 4.1.2 on 2022-11-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_phonenumber_personalinfo_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='avatar',
            field=models.ImageField(default='man.png', null=True, upload_to=''),
        ),
    ]
