# Generated by Django 4.1.2 on 2022-11-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_personalinfo_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='avatar',
            new_name='profile_pic',
        ),
    ]
