# Generated by Django 4.1.2 on 2023-03-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_workratings_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workratings',
            name='customerId',
            field=models.CharField(max_length=100),
        ),
    ]
