# Generated by Django 4.1.2 on 2023-03-20 08:22

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_workratings_customerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workratings',
            name='customerId',
            field=models.CharField(max_length=100, verbose_name=django.contrib.auth.models.User),
        ),
    ]
